version: '3'

services:
  web:
    image: nginx:alpine
    container_name: docker-web
    ports:
      - PORT:80
    volumes:
      - ./nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ../www:/var/www/html
    depends_on:
      - app

  app:
    build: php
    container_name: docker-app
    volumes:
      - ../www:/var/www/html

  database:
    image: mysql:8.0.31
    container_name: docker-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: laravel
