FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo_mysql
    
RUN pecl install xdebug && docker-php-ext-enable xdebug

ADD /conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
